---
Name: news
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverStripers\News\Extensions\Configs
PageController:
  extensions:
    - SilverStripers\News\Extensions\NewsPageExtension
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripers\News\Extensions\NewsHierarchy
